repos:
  # Python formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^report/.*\.py$

  # Python import sorting with isort
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        language_version: python3.12
        files: ^report/.*\.py$

  # Terraform formatting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
        files: ^infra/.*\.(tf|tfvars)$

  # Ensure package-lock.json is in sync with package.json
  - repo: local
    hooks:
      - id: npm-lock-sync
        name: Check npm lockfile consistency
        entry: bash -c 'npm install --package-lock-only --ignore-scripts --no-audit --no-fund && git diff --exit-code package-lock.json || (echo "❌ package-lock.json out of sync! Run npm install and recommit." && exit 1)'
        language: system
        pass_filenames: false
        files: ^app\.json$